#!/usr/bin/env python
# __Author__:cmustard

import bs4
import urllib.request
import urllib.parse
import gzip
from random import choice

from util.userAgent import pcUserAgent
from util.comm import getLogger,printInfo

class PluginBase:
    def __init__(self):
        self.url = None  # 目标URL
        self.cms_name = None  # cms对应名称
        self.version = None   # cms版本结果
        self.body = None  # 返回的body
        self.static_uri = None  # 需要验证的uri
        self.uri_md5 = None  # 对应uri的md5值
        self.regx = None   # 正则匹配
        self.headers = None  # 头部匹配
        self.title = None   # title匹配
        self.encodeList = ("utf-8", "gb2312", "gbk", "big5")
        self.logger = getLogger()

    def start(self):
        pass

    def verify(self):
        """
        该函数需要自己实现
        :return:
        """
        """
        
        """
        matchs = [
            {"title":'glamor","body":"<name>'},
            {"version":'<meta name="generator" content="Generic CMS version ([a-z0-9])+'},
            {"body",'This page was generated by <b>Generic CMS</b>'},
            {"header":"server:cms"},
            {"static":"/uri","md5":"12313123123"},
            {"head":"asdasd"},
            {"text":"123"}, # body and head
        ]
        raise NotImplementedError

    def output(self):
        """
        该函数需要自己实现,返回一个output字典
        :return:
        """
        raise NotImplementedError



    def _htmlParser(self):
        self.urlparse = urllib.parse.urlparse(self.url)
        if self.urlparse.scheme != "http" and self.urlparse.scheme != "https":
            self.url = "{}://{}".format("http",self.url)

        if self.static_uri is not None:
            self.static_uri = urllib.request.quote(self.static_uri)
            self.url = "{}/{}".format(self.url,self.static_uri)
        print(self.url)

        req = urllib.request.Request(self.url)
        req.add_header("User-Agent",pcUserAgent[choice(list(pcUserAgent.keys()))])
        # req.add_header("cookie","none\r\n")
        req.add_header("Accept-Encoding", "gzip, deflate")
        req.add_header("Referer", self.url)
        raw_html_object = urllib.request.urlopen(req)
        raw_html_contents = raw_html_object.read()
        # get headers from server
        self.raw_headers = raw_html_object.headers

        self.contents = self.gzip(raw_html_contents)
        print(len(self.contents),self.raw_headers)
        self._parser()



    def _parser(self):

        try:
            bs_object = bs4.BeautifulSoup(self.contents, "html.parser")
            self.raw_body = str(bs_object.body)
            self.raw_title = bs_object.title.get_text()
            self.raw_head = str(bs_object.head)
            # print(type(self.raw_body))
        except Exception as e:
            self.logger.warn(printInfo(__file__,"_parser function: "+str(e)))
            self.raw_body = None
            self.raw_title = None
            self.raw_head = None

    def gzip(self,contents):
        if isinstance(contents, bytes):
            # print(isinstance(body,bytes))
            for code in self.encodeList:
                try:
                    # gzip decompress
                    try:
                        contents = gzip.decompress(contents).decode(code)
                        break
                    except OSError as e:
                        self.logger.debug(printInfo(__file__, str(e)))
                        contents = contents.decode(code)
                        break

                except UnicodeDecodeError as e:
                    self.logger.debug(printInfo(__file__, str(e)))
                    continue

                except Exception as e:
                    self.logger.warning(printInfo(__file__, str(e)))
                    contents = ""
        return contents

    def test(self):
        self.url = "www.glamor.site"
        # self.static_uri = "/2.txt"
        self._htmlParser()


if __name__ == '__main__':
    t = PluginBase()
    t.test()